search: "🔍"
lyrics: "📃"
arrow_left: "◀️"
arrow_right: "▶️"
double_arrow_left: "⏪"
double_arrow_right: "⏩"
music_resume: "▶️"
music_pause: "⏸️"
music_loop: "🔁"
music_next: "⏭️"
music_previous: "⏮️"
note_stalled: "⏳"
note_finished: "✅"
note_ongoing: "🔄"
note_remove: "❌"
note_unbegan: "🚫"
